(package "atl-long-lines"
         "0.2.0"
         "Turn off truncate-lines when the line is long")

(website-url "https://github.com/jcs-elpa/atl-long-lines")
(keywords "truncate" "lines" "auto" "long")

(package-file "atl-long-lines.el")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
